# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171105_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, 'Мужчина'), (1, 'Женщина'), (2, 'Не определено')], default=2),
        ),
        migrations.AlterField(
            model_name='participant',
            name='social_network_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
