# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171105_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='process',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
