# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171105_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='json',
            new_name='typed_content',
        ),
        migrations.RemoveField(
            model_name='event',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='questions_answers',
        ),
        migrations.AddField(
            model_name='question',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Questionnaire'),
        ),
    ]
