# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171109_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='process_html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='rules_html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
