# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171125_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='age',
        ),
    ]
