# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171125_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Event'),
        ),
    ]
