# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_group_locked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date_delivered',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='date_opened',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='date_sended',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='event',
        ),
        migrations.AddField(
            model_name='notification',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider_mail_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sended_to_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='temporary_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Email confirmation'), (1, 'Participation confirmation'), (2, 'Send ward')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
