# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20171126_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='failed',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='opened',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sended_to_provider',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='temporary_failed',
        ),
        migrations.AddField(
            model_name='notification',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Created'), (1, 'SendedToProvider'), (2, 'Accepted'), (3, 'Delivered'), (4, 'TemporaryFailed'), (5, 'Failed'), (6, 'Opened'), (7, 'Clicked')], default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
    ]
