# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20171217_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='KVParams',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
    ]
