# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_kvparams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Created'), (1, 'SendedToProvider'), (2, 'RejectedByProvider'), (3, 'Accepted'), (4, 'Delivered'), (5, 'TemporaryFailed'), (6, 'FailedPermanently'), (7, 'Opened'), (8, 'Сomplained'), (9, 'Clicked')], default=0),
        ),
    ]
