# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20171217_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvparams',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'text'), (1, 'datetime')], default=0),
        ),
    ]
