# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_kvparams_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Rejected'), (2, 'Accepted'), (3, 'TemporaryFailed'), (4, 'FailedPermanently'), (5, 'Delivered'), (6, 'Opened')], default=0),
        ),
    ]
