# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20171219_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Registered'), (1, 'EmailConfirmationSent'), (2, 'EmailConfirmed'), (3, 'ConfirmationSent'), (4, 'Confirmed'), (5, 'WardAssigned'), (6, 'WardSent')], default=0),
        ),
    ]
